Foodshare/Models/Donation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Foodshare.Models
{
    public class Donation
    {
        public int DonationId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public string Location { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime AvailableFrom { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime AvailableTo { get; set; }

        public string DonatedById { get; set; }
        public virtual ApplicationUser DonatedBy { get; set; }

        public string Contact { get; set; }
        public string Phone { get; set; }

        public string ImageUrl { get; set; }

        public string ClaimedById { get; set; }
        public virtual ApplicationUser ClaimedBy { get; set; }

        public bool IsDeleted { get; set; }
    }
}

Foodshare/Controllers/DonationsController.cs
using Foodshare.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Foodshare.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Net.Mail;
using System.Configuration;
using Foodshare.Helper;

namespace Foodshare.Controllers
{
    [RequireHttps]

    [Authorize]
    public class DonationsController : Controller
    {
        private FoodshareDbContext db = new FoodshareDbContext();

        // GET: Forum
        public ActionResult Index()
        {
            var yesterday = DateTime.Now.AddDays(-1);

            var userId = User.Identity.GetUserId();

            var phoneNumber = db.Users.Where(x => x.Id == userId).Select(x => x.PhoneNumber).SingleOrDefault();

            if (User.IsInRole("Agency"))
            {
                if (String.IsNullOrWhiteSpace(phoneNumber))
                {
                    return RedirectToAction("EditPhoneNumber", "Manage");
                }
            }

            var verifiedEmail = db.Users.Where(x => x.Id == userId).Select(x => x.EmailConfirmed).SingleOrDefault();

            var items = new List<Donation>();

            if (User.IsInRole("Administrator"))
            {
                items = db.Donations.OrderByDescending(x => x.DonationId).Take(50).ToList();
            }
            else
            {
                if (User.IsInRole("Agency"))
                {
                    items = db.Donations.Where(x => !x.IsDeleted && x.AvailableTo > yesterday).OrderByDescending(x => x.AvailableTo).ToList();
                }
                else
                {
                    items = db.Donations.Where(x => !x.IsDeleted && x.AvailableTo > yesterday).Where(x => x.DonatedById == userId).OrderByDescending(x => x.AvailableTo).ToList();
                }
            }

            ViewBag.UserId = userId;
            ViewBag.EmailConfirmed = verifiedEmail;

            return View(items);
        }

        public ActionResult Edit(int? id)
        {
            var donation = new Donation();

            var userId = User.Identity.GetUserId();

            var prevDonation = db.Donations.Where(x => x.DonatedById == userId).OrderByDescending(x => x.DonationId).FirstOrDefault();

            if (prevDonation != null)
            {
                donation.Location = prevDonation.Location;
                donation.Phone = prevDonation.Phone;
            }

            donation.AvailableFrom = DateTime.Now;
            donation.AvailableTo = DateTime.Now.AddHours(3);

            if (id.HasValue)
            {
                donation = db.Donations.Where(x => x.DonationId == id.Value).SingleOrDefault();


            }
            

            return View(donation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Donation donation)
        {
            if (ModelState.IsValid)
            {
                var sendEmail = false;


                var uploads = Server.MapPath("~/content/uploads");
                var image = Request.Files["DonationImage"];

                if (image != null && image.ContentLength > 0)
                {
                    if (!Directory.Exists(uploads))
                    {
                        Directory.CreateDirectory(uploads);
                    }

                    image.SaveAs(uploads + "\\" + image.FileName);
                    donation.ImageUrl = "/content/uploads/" + image.FileName;
                }



                if (donation.DonationId == 0)
                {
                    db.Donations.Add(donation);
                    donation.DonatedById = User.Identity.GetUserId();
                    sendEmail = true;
                }
                else
                {
                    db.Entry(donation).State = System.Data.Entity.EntityState.Modified;
                }

                
                db.SaveChanges();

                //donation.DonatedBy.PhoneNumber = donation.Phone;
                //db.SaveChanges();
                try
                {
                    if (sendEmail)
                    {
                        var message = new MailMessage();

                        message.To.Add(ConfigurationManager.AppSettings["donationsEmail"]);

                        var agencyRole = db.Roles.Where(x => x.Name == "Agency").SingleOrDefault();

                        if (agencyRole != null)
                        {
                            var userIds = agencyRole.Users.Select(x => x.UserId).ToList();

                            var users = db.Users.Where(x => userIds.Contains(x.Id) && x.EmailConfirmed).Select(x => x.Email).ToList();

                            foreach (var user in users)
                            {
                                message.Bcc.Add(new MailAddress(user));
                            }


                        }

                        var domainName = Request.Url.GetLeftPart(UriPartial.Authority);


                        message.Subject = "New Donation Available: " + donation.Title;
                        message.Body = "A new donation has been added at " + domainName + "\r\n\r\nTitle: " + donation.Title + "\r\nDescription: " + donation.Description + "\r\nLocation: " + donation.Location;

                        using (var smtpClient = new SmtpClient())
                        {
                            try
                            {
                                // I've learnt my lesson with public repos. ;)
                                System.Net.NetworkCredential credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["emailUsername"], ConfigurationManager.AppSettings["emailPassword"]);
                                smtpClient.Credentials = credentials;

                                smtpClient.Send(message);
                            }
                            catch { }
                        }
                    }
                }
                catch (Exception ex)
                { }

                return RedirectToAction("Index");
            }


            return View(donation);
        }


        [Authorize(Roles = "Agency")]
        public ActionResult Claim(int id)
        {
            var donation = db.Donations.Where(x => x.DonationId == id).SingleOrDefault();
            var userId = User.Identity.GetUserId();

            ViewBag.UserId = userId;

            return View(donation);
        }

        [Authorize(Roles = "Agency")]
        public ActionResult ConfirmClaim(int id)
        {
            var donation = db.Donations.Where(x => x.DonationId == id).SingleOrDefault();
            var userId = User.Identity.GetUserId();

            if (donation.ClaimedById == null)
            {
                // we can claim it!
                donation.ClaimedById = userId;
                db.SaveChanges();

                var body = "<h1>Great News!</h1>" +
                    "<p>Your donation has been claimed by:</p>" +
                    "<p><b>Email:</b> " + donation.ClaimedBy.Email + "</p>" +
                    "<p><b>Telephone:</b> " + donation.ClaimedBy.Telephone + "</p>" +
                    "";

                // now send notification
                EmailHelper.SendEmail(donation.DonatedBy.Email, "Your donation has been claimed.", body);


                var between = donation.AvailableFrom.ToString("dd MMM yyyy");

                if (donation.AvailableFrom.Date == donation.AvailableTo.Date)
                {
                    between += " " + donation.AvailableFrom.ToString("HH:mm") + " - " + donation.AvailableTo.ToString("HH:mm");
                }
                else
                {
                    between += " " + donation.AvailableFrom.ToString("HH:mm") + " - " + donation.AvailableTo.ToString("dd MMM yyyy") + " " + donation.AvailableTo.ToString("HH:mm");
                }

                body = "<h1>Donation Claimed</h1>" +
                    "<p><b>Description:</b> " + donation.Description + "</p>" +
                    "<p><b>Location:</b> " + donation.Location + "</p>" +
                    "<p><b>Contact Email:</b> " + donation.DonatedBy.Email + "</p>" +
                    "<p><b>Contact Phone:</b> " + donation.Phone + "</p>" +
                    "<p><b>Collection Date/Time:</b> " + between + "</p>" +
                    "";

                EmailHelper.SendEmail(donation.ClaimedBy.Email, "You've claimed this donation.", body);

            }


            return RedirectToAction("Claim", new { id = id });
        }

    }
}

Foodshare/Views/Donations/Claim.cshtml
@model Foodshare.Models.Donation
@{
    ViewBag.Title = "Donation Details";
}

@section scripts{

    <script>

        $(function () {
            updateCountdowns();
        });


        function updateCountdowns() {
            $('.countdown').each(function (index, value) {

                var finish = $(value).attr('data-finish');

                var eventTime = moment(finish, 'DD-MM-YYYY HH:mm:ss').unix();
                var currentTime = moment().unix();
                var diffTime = eventTime - currentTime;
                var duration = moment.duration(diffTime * 1000, 'milliseconds')

                var h = moment.duration(duration).hours();
                var m = moment.duration(duration).minutes();
                var s = moment.duration(duration).seconds();

                $(value).text(h + ' hours ' + m + ' minutes ' + s + ' seconds')

            });

            setTimeout(updateCountdowns, 1000);
        }

    </script>

}


<h2>Claim Donation</h2>

<div class="row" style="margin-top: 1em;">
    <div class="col-xs-12 col-sm-3 ">
        <img src="@Html.DisplayFor(modelItem => Model.ImageUrl)" style="width: 100%; max-height: 500px; margin: 0 auto;" />
    </div>
    <div class="col-xs-12 col-sm-6">
        <h2>@Html.DisplayFor(modelItem => Model.Title)</h2> <br>
        <p>
            @Html.DisplayFor(modelItem => Model.Location)<br>
            @Html.DisplayFor(modelItem => Model.Description)
        </p>

        <div><strong>Date:</strong> @Model.AvailableFrom.ToString("dd MMM yyyy") <strong>Time:</strong> between @Model.AvailableFrom.ToString("HH:mm") and @Model.AvailableTo.ToString("HH:mm")</div>


    </div>
    <div class="col-xs-12 col-sm-3">
        @if (User.IsInRole("Agency") && Model.ClaimedById == null && Model.AvailableTo > DateTime.Now && Model.DonatedById != ViewBag.UserId)
            {
            <p><strong>Remaining:</strong></p>
                            <p>
                                <span class="countdown" data-finish="@Model.AvailableTo.ToString("dd-MM-yyyy HH:mm:ss")"></span>
                            </p>

            <p style="margin-top: 1em;"><a class="btn btn-default btn-lg" href="@Url.Action("ConfirmClaim", new { id = Model.DonationId })"><span class="glyphicon glyphicon-heart"></span> Commit to pickup</a></p>
        }

        @if (Model.AvailableTo < DateTime.Now)
            {
            <p style="margin-top: 1em;" class="text-danger">Donation is no longer available</p>
        }

        @if (Model.ClaimedById != null && Model.ClaimedById != ViewBag.UserId)
            {
            <p style="margin-top: 1em;" class="text-danger">Donation has been claimed </p>
        }

        @if (Model.ClaimedById != null && Model.ClaimedById == ViewBag.UserId)
            {
            <p><strong>Pickup Within:</strong></p>
                        <p>
                            <span class="countdown" data-finish="@Model.AvailableTo.ToString("dd-MM-yyyy HH:mm:ss")"></span>
                        </p>

            <p style="margin-top: 1em;" class="text-success">You have claimed this Donation</p>
        }

    </div>
</div>

Foodshare/Views/Donations/Edit.cshtml
@model Foodshare.Models.Donation
@{

    if (Model.DonationId > 0)
    {
        ViewBag.Title = "Edit Donation";
    }
    else
    {
        ViewBag.Title = "Add New Donation";
    }

}

@section head{

    @Styles.Render("~/Content/datetime")

}

@section scripts{

    <script type="text/javascript">


        $(function () {

            $('.date').datetimepicker({
                locale: 'en-au',
                format: 'DD/MM/YYYY h:mm A'
            });

        });


    </script>

}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Donations", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.DonationId)
    @Html.HiddenFor(m => m.ImageUrl)
    @Html.HiddenFor(m => m.DonatedById)

    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control", placeholder = "A short title describing the item" })
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Image</label>
        <div class="col-md-10">
            <input type="file" name="DonationImage" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = "8", placeholder = "A fuller description of item\r\n\r\nInclude:\r\n- " })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Location, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Location, new { @class = "form-control", placeholder = "Street Address ideally" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Phone, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Phone, new { @class = "form-control", placeholder = "Contact Telephone" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.AvailableFrom, "Available From", new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <div class='input-group date' id='datetimepicker6'>
                @Html.TextBoxFor(m => m.AvailableFrom, new { @class = "form-control", placeholder = "From this date/time" })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>

        @Html.LabelFor(m => m.AvailableTo, "Available Until", new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <div class='input-group date' id='datetimepicker7'>
                @Html.TextBoxFor(m => m.AvailableTo, new { @class = "form-control", placeholder = "To this date/time" })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            @if (Model.DonationId == 0)
            {
                <input type="submit" class="btn btn-default" value="Add new donation" />
            }
            else
            {
                <input type="submit" class="btn btn-default" value="Update donation" />
            }


        </div>
    </div>
}

Foodshare/Views/Donations/Index.cshtml
@model IEnumerable<Foodshare.Models.Donation>

@{
    ViewBag.Title = "Donations";
}

@section scripts{
    
<script>

    $(function () {
        updateCountdowns();
    });


    function updateCountdowns()
    {
        $('.countdown').each(function (index, value) {

            var finish = $(value).attr('data-finish');

            var eventTime = moment(finish, 'DD-MM-YYYY HH:mm:ss').unix();
            var currentTime = moment().unix();
            var diffTime = eventTime - currentTime;
            var duration = moment.duration(diffTime * 1000, 'milliseconds')

            var h = moment.duration(duration).hours();
            var m = moment.duration(duration).minutes();
            var s = moment.duration(duration).seconds();

            $(value).text(h + ' hours ' + m + ' minutes ' + s + ' seconds')

        });

        setTimeout(updateCountdowns, 1000);
    }

</script>    
    
}

<h2>Donations</h2>

@if (!ViewBag.EmailConfirmed)
{
<div class="row">
    <div class="col-xs-12 text-danger"><h3>Warning: You won't get any notifications until you verify your email</h3></div>
</div>
}

@if (User.IsInRole("Agency") || User.IsInRole("Administrator"))
{
    <div class="row">

        <div class="col-xs-12">

            <div class="well">
                <ul>
                    <li><a target="_blank" href="~/Content/guidelines-for-donations-of-cooked-or-prepared-food.pdf">Guidelines for donations of cooked or prepared food</a></li>
                    <li><a target="_blank" href="~/Content/label-for-donated-prepared-food.docx">Label for donated prepared food</a></li>
                </ul>
            </div>

        </div>

    </div>
}



<div class="row">
    <div class="col-xs-12 text-right">

        <a class="btn btn-danger btn-lg" href="@Url.Action("Edit" )"><span class="glyphicon glyphicon-plus"></span> New Donation</a>

    </div>

</div>

@if (User.IsInRole("Agency") && Model.Where(x => x.ClaimedById == null && x.AvailableTo > DateTime.Now).Count() == 0)
{
    <div class="row">
        <div class="col-xs-12">

            <h3>No Available Donations</h3>
            <div class="text-info">
                <p>Currently there are no donations available. However as soon as a supplier lists a new donation, you'll get a notification via email.</p>
                <p>If you, as an Agency, have excess food, you can also list it here as a donation that other Agencies can claim.</p>
            </div>

        </div>
    </div>
}


@foreach (var item in Model) {


<div class="@((item.ClaimedById != null && item.ClaimedById == ViewBag.UserId) ? "panel panel-success" : "")" style="margin-top: 1em;padding-bottom: 1em;">


    <div class="row" style="margin-top: 1em;">
        <div class="col-xs-12 col-sm-3 ">
            <img src="@Html.DisplayFor(modelItem => item.ImageUrl)" style="width: 100%; max-height: 500px; margin: 0 auto;" />
        </div>
        <div class="col-xs-12 col-sm-6">
            <h2>@Html.DisplayFor(modelItem => item.Title)</h2> <br>
                                                               <p>
                                                                   <strong>Location:</strong> @Html.DisplayFor(modelItem => item.Location)</p><p><strong>Description: </strong><br/>
                                                                   @Html.DisplayFor(modelItem => item.Description)
                                                               </p>

            <div><strong>Date:</strong> @item.AvailableFrom.ToString("dd MMM yyyy") <strong>Time:</strong> between @item.AvailableFrom.ToString("HH:mm") and @item.AvailableTo.ToString("HH:mm")</div>
        </div>
        <div class="col-xs-12 col-sm-3">

            @if (item.DonatedById == ViewBag.UserId)
    {
        <p style="margin-top: 1em;"><a class="btn btn-default" href="@Url.Action("Edit", new { id = item.DonationId })">Edit</a></p>
}

            @if (User.IsInRole("Agency") && item.ClaimedById == null && item.AvailableTo > DateTime.Now && item.DonatedById != ViewBag.UserId)
    {
        <p><strong>Remaining:</strong></p>
        <p>
            <span class="countdown" data-finish="@item.AvailableTo.ToString("dd-MM-yyyy HH:mm:ss")"></span>
        </p>
        <p style="margin-top: 1em;"><a class="btn btn-default btn-lg" href="@Url.Action("Claim", new { id = item.DonationId })"><span class="glyphicon glyphicon-heart"></span> Claim</a></p>
}

            @if (item.AvailableTo < DateTime.Now)
    {
        <p style="margin-top: 1em;" class="text-danger">Donation is no longer available</p>
}

            @if (item.ClaimedById != null && item.ClaimedById != ViewBag.UserId)
    {
        <p style="margin-top: 1em;" class="text-danger">
            Donation has been claimed @if (User.IsInRole("Administrator"))
    {<span>by @item.ClaimedBy.Email</span>}
        </p>
}

            @if (item.ClaimedById != null && item.ClaimedById == ViewBag.UserId)
    {
        <p><strong>Pickup Within:</strong></p>
        <p>
            @if (item.AvailableTo > DateTime.Now)
    {
        <span class="countdown" data-finish="@item.AvailableTo.ToString("dd-MM-yyyy HH:mm:ss")"></span>
}
else
{
        <span class="text-warning">This item is overdue to be picked up.</span>
}
        </p>

        <p style="margin-top: 1em;" class="text-success">You have claimed this Donation</p>

        <p><strong>Contact:</strong> @item.DonatedBy.Email</p>
        <p><strong>Telephone:</strong> @item.Phone</p>

}
        </div>
    </div>

</div>


    }



   